version: '2'
services:
  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    environment:
      PUID: "114"
      GUID: "119"
      TZ: "America/Indiana/Indianapolis"
    volumes:
      - /opt/unifi_config:/config
      - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped
#    tty: true
